### ISSUE TITLE
Issue with "Lua by sumneko" Extension

### ISSUE THREAD

**Issue by NopeImNotHere** [MCJack123/vscode-craftos-pc#28] opened 2024-12-26 18:58 UTC
Hey,
I've been trying out your Extension, and I'm impressed it works pretty flawlessly so far.
Sadly, I faced an Issue with the Plugin you recommended, that being “[Lua by sumneko](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) for Lua syntax highlighting & linting”.
It constantly tries to search the directory of the Root Directory, I'm guessing that the Connections are handled by opening a web socket / virtual File System and reading and updating from there, but it seems to not correctly be revealing it to the system. And thus reverting to last known location being Root.
![screenshot_2024-12-26_19-22-02_564066158](https://github.com/user-attachments/assets/c55f88e9-76dd-422a-9f22-6831d9c5d75c)

```
OS: Arch Linux x86_64
Kernel: Linux 6.12.6-arch1-1
```

```fish
$ craftos --version
CraftOS-PC v2.8.3
Built with: cli webp mixer print_html
Copyright (c) 2019-2024 JackMacWindows. Licensed under the MIT License.
```

![screenshot_2024-12-26_19-57-01_486153974](https://github.com/user-attachments/assets/332baa65-1ea2-49f5-a253-a6e1400a00b3)

**Comment by MCJack123** [comment] 2024-12-26 19:11
Duplicate of #13

**Closed as not planned by MCJack123** 2024-12-26 19:11 UTC
